### ISSUE TITLE
Plugins?

### ISSUE THREAD

**Issue by loukaniko85** [coreruleset/coraza-crs-docker#10]
Hi Team - anyway to get modsecurity plugins to function?

-- Want to jump to this from the modsecurty-crs container, but the plugins are holding me back.

**Comment by fzipi** [comment]
What about mounting the proper directories inside the container?

**Comment by fzipi** [comment]
See https://github.com/coreruleset/coraza-crs-docker/blob/main/src/templates/Caddyfile#L24-L30 for example. You should only need to bind mount the directory where you downloaded your plugins to the `/opt/coraza/owasp-crs/plugins/` directory.

**Comment by loukaniko85** [comment]
I've tried this, not sure the plugins get loaded. Same plugins folder as my modsec container, which works.

**Comment by loukaniko85** [comment]
![image](https://github.com/user-attachments/assets/a590ff43-1162-4649-a6b9-a39e2c0ab440)

**Comment by loukaniko85** [comment]
![image](https://github.com/user-attachments/assets/912d0143-5d5f-4223-9ac2-fba3b03713d0)

**Comment by fzipi** [comment]
Do you have nextcloud installed? Can you test?

**Comment by loukaniko85** [comment]
Of course I do; I am using the modsecurity-crs container at the moment, including the nextcloud plugin, as above, and its working as expected. Ive unmapped and remapped the plugins folder to test, and enable and disabled the plugin in the config itself. Works as expected with this container, certain features of nextcloud are denied with the plugin disabled.

Though with the coraza-crs container, doing the same tests, it never seems to be enabled and the certain features of nextcloud are always denied.

**Comment by fzipi** [comment]
Thanks for confirming! I'll check it out and see what is happening then.

**Comment by loukaniko85** [comment]
Happy to. Here if you need anything further.

**Comment by fzipi** [comment]
Did some reorganization and better output and docs in https://github.com/coreruleset/coraza-crs-docker/pull/14.

You can start testing as soon as it is merged and the new container is out!
