### ISSUE TITLE
Latest Build Error - ${CORAZA_DEBUG_LOGLEVEL}": invalid syntax

### ISSUE THREAD

**Issue by loukaniko85** [coreruleset/coraza-crs-docker#16]
Thank you for adding the plugin support - looking forward to trying the latest build. However, the latest push seems to have broken my container.

Error below.

{"level":"info","ts":1722762449.3306267,"msg":"using config from file","file":"/etc/caddy/Caddyfile"}
{"level":"info","ts":1722762449.3312898,"msg":"adapted config to JSON","adapter":"caddyfile"}
{"level":"info","ts":1722762449.332384,"logger":"admin","msg":"admin endpoint started","address":"localhost:2019","enforce_origin":false,"origins":["//localhost:2019","//[::1]:2019","//127.0.0.1:2019"]}
{"level":"info","ts":1722762449.3325653,"logger":"tls.cache.maintenance","msg":"started background certificate maintenance","cache":"0xc0001de200"}
{"level":"info","ts":1722762449.3336425,"logger":"tls.cache.maintenance","msg":"stopped background certificate maintenance","cache":"0xc0001de200"}
**Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'waf': provision http.handlers.waf: invalid WAF config: strconv.Atoi: parsing "${CORAZA_DEBUG_LOGLEVEL}": invalid syntax**
Generating configuration files...
  - Caddyfile
    - Generating Caddyfile from template /templates/Caddyfile
    - Done
  - Coraza configuration file
    - Generating Caddyfile from template /templates/coraza.conf
    - Done
  - No user configuration files found in /opt/coraza/config.d
  - User plugins loaded from /opt/coraza/plugins
    -> dos-protection-before.conf
    -> dos-protection-config.conf
    -> nextcloud-rule-exclusions-before.conf
    -> nextcloud-rule-exclusions-config.conf
    - Done
  - No user defined rule sets found in /opt/coraza/rules.d
Launching caddy run --config /etc/caddy/Caddyfile --adapter caddyfile

**Comment by fzipi** [comment]
Ugh.. I think I've removed that variable 🤦 Weird that it didn't show in the build process.

Let me add it back again.

**Comment by loukaniko85** [comment]
Still broken.

Error: loading initial config: loading new config: loading http app module: provision http: server srv0: setting up route handlers: route 0: loading handler modules: position 0: loading module 'waf': provision http.handlers.waf: invalid WAF config: syntax error for directive SecUploadKeepFiles: syntax error: [on/off]

**Comment by fzipi** [comment]
Ouch, I might have broken it? 🤔 Will fix tomorrow.
